### ISSUE TITLE
Showroom crash on new version

### ISSUE THREAD

**Issue by FranK45** [gRally/dev#372]
When clicking to select livery, I receive an error with indication that the game has crashed. I then receive a white box instead of the showroom.

**Comment by ghiboz** [comment]
@punker76 I assign you this issue... at the moment is fixed but not in a good way..
the issue is that I need an handle to write into the unity showroom... I don't know if is the new unity version that create this issue or something new about childwindow..
the code is into `carPaint.xaml.cs` in a `LoadCar();` function.

**Comment by ghiboz** [comment]
@punker76 it's a Unity issue, not our:
https://forum.unity3d.com/threads/launch-unity-with-parenthwnd-crash-now.446961/#post-2894594
we wait!

**Comment by GBratsos** [comment]
On Livery selection the car is not centered. Maybe we need to increase the width of the window,
![livery](https://cloud.githubusercontent.com/assets/3661790/24871368/0d275570-1e22-11e7-9248-b99634dc5bc7.jpg)
