### ISSUE TITLE
gRallysim.exe crashes when clicking drive

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#536]
# User: chuky
---
The game crashes when I click drive from the launcher. It's a fresh install, I didn't change anything in the config.

[log](https://www.grally.net/u/uploads/ba70ccb3141b758a06b01d1fe1d8c889dcbe1158.zip)

**Comment by ghiboz** [comment]
can you look if in steam folder there's `gRallySim.exe`?
'cause I can't see the log of the game

**Comment by chuky500** [comment]
I'm the one who reported this issue. I have gRallySim.exe in C:\Program Files (x86)\Steam\steamapps\common\gRally

If I run gRally with steam, when I click drive it says gRallySim.exe crashed. But if I run gRallySim.exe without starting gRally it doesn't crash. It opens fine and there's a red message in game telling me "login failed! check steam connection and please launch gRally menu".

In the gRally menu, I can chose the livery of cars and change colors and go back to the menu.

The first time I ran gRally through steam, the menu told me that my steam account wasn't checked or wasn't linked to an account on the forum or something like that. Maybe that's what's causing the issue. When I click my steam icon on the top right corner, I was seeing chuky chuky the italian flag (I'm not italian) and my picture, but I couldn't edit these informations. After I quit and deleted my documents/gRally now I see the same but I also see O+ which wasn't there before.

Also something that may be linked to the issue is that the settings in the menu don't seem to do anything to the gRallySim.exe window. If I change resolution or pick fullscreen, the gRallySim window is still windowed and not in my resolution. The only way to have fullscreen at the moment for me is to press alt-enter, and now everytime it's in fullscreen (even if I change the options in the menu).
